spring:
  application:
    name: authentication
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authentication}
    username: ${DB_USERNAME:authentication_svc}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 3000
      validation-timeout: 2000
      initialization-fail-timeout: -1

server:
  port: 8000
  shutdown: graceful

auth:
  google:
    client-id: ${AUTH_GOOGLE_CLIENT_ID:}
    client-secret: ${AUTH_GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${AUTH_GOOGLE_REDIRECT_URI:}
